---
- name: Play | Check to see if activator download exists
  stat:
    path: /opt/tmp/typesafe-activator-1.2.10-minimal.zip
  register: play_framework_download_check

- name: Play | download activator
  get_url:
    dest: /tmp/
    url: "http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10-minimal.zip"
  register: play_framework_downloaded
  when: play_framework_download_check.stat.exists == false

- name: Play | extract activator to /opt/typesafe
  command: "unzip -n /tmp/typesafe-activator-1.2.10-minimal.zip -d /opt/typesafe"
  when: play_framework_downloaded|changed

- name: Play | update link to latest extract
  file:
    src="/opt/typesafe/activator-1.2.10-minimal"
    dest=/opt/typesafe/playframework
    state=link
  when: play_framework_downloaded|changed

- name: Play | correct activator ownership
  file:
    path="/opt/typesafe/activator-1.2.10-minimal"
    owner={{ play_framework_username }}
    recurse=yes
    state=directory
  when: play_framework_downloaded|changed